### ISSUE TITLE
packagist download?

### ISSUE THREAD

**Issue by rafa-acioly** [d4sign/d4sign-php#1]
Para facilitar o uso do pacote com frameworks seria mais viável coloca-lo no versionamento atraves do `packagist.org`, o que acham? O unico pacote que entrei no `packagist` é este: https://packagist.org/packages/d4sign/d4sign

Que não aponta para este repositório e sim para: https://github.com/phelipemomesso/d4sign

**Comment by d4sign** [comment]
Olá, bom dia!

Agradecemos a recomendação e encaminhamos para o nosso departamento de
desenvolvimento tomar as providências.

Qualquer dúvida estamos a disposição.

Abraços,



2017-12-18 16:08 GMT-02:00 Rafael Acioly <notifications@github.com>:

**Comment by rafa-acioly** [comment]
Jóia! por enquanto estou usando um pacote que criei a partir do código fonte de vocês.

abraços;


https://packagist.org/packages/rafa-acioly/d4sign-php
