### ISSUE TITLE
Erro ao compilar com o composer 2.0

### ISSUE THREAD

**Issue by caiovncius** [d4sign/d4sign-php#7]
Ao instalar o pacote com o composer 2.0, o composer não instala.

Class D4sign\Client located in ./vendor/d4sign/d4sign-php/sdk/src/D4sign/Client.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by marceloamp2** [comment]
Mesmo problema

**Comment by Dessaaa** [comment]
Comigo também, alguma solução?

**Comment by guilhermejp** [comment]
> Ao instalar o pacote com o composer 2.0, o composer não instala.
> 
> Class D4sign\Client located in ./vendor/d4sign/d4sign-php/sdk/src/D4sign/Client.php does not comply with psr-4 autoloading standard. Skipping.

Tive o mesmo problema, o que fiz foi remover a pasta D4sign, jogar tudo para um nível acima:
de:  vendor/d4sign/d4sign-php/sdk/**src/D4sign/....**
para: vendor/d4sign/d4sign-php/sdk/**src/....**

_(faça isso com cuidado pois qualquer composer update mata a alteração!!!)_

**Comment by atiladelcanton** [comment]
Nenhuma posição do time, da D4 quanto a esse problema :(

**Comment by lincolnfpsantos** [comment]
Mesmo problema.

**Comment by lincolnfpsantos** [comment]
Criei um pull-request com a correção. #8
